

export const SET_CAR_LIST = "SET_CAR_LIST";

export const INIT_ALL_CARS = "INIT_ALL_CARS"
export const PREPARE_FOR_DETAIL = "PREPARE_FOR_DETAIL"
export const SET_HELP_STATE = "SET_HELP_STATE"
export const GET_CUSTOM_INFO = "GET_CUSTOM_INFO";
export const SET_CAR_ID_INFO = "SET_CAR_ID_INFO";
export const SET_CAR_ID_FAILED = "SET_CAR_ID_FAILED"
export const SET_START_LIST = "SET_START_LIST"
export const SET_START_LIST_FAIL = "SET_START_LIST_FAIL"
export const GET_PERSON_NOTES = "GET_PERSON_NOTES"
export const GET_PERSON_NOTES_F = "GET_PERSON_NOTES_F"